### PR TITLE
Arc distance julia

### PR DESCRIPTION
**Pull request by aterrel**
From @serge-sans-paille

"""
I gave it a try in 

https://github.com/serge-sans-paille/python-benchmarks 

using a small makefile infrastructure to run static compilers when 
needed (cython & pythran). 

It's completely linux-centric... 

I started with the allmighty julia fractal code, from the cython 
tutorial given by Kurt during Scipy. Yuancheng added the arc_distance 
code. 

I failed to get good performance with numba and encountered an error 
with parakeet, so feel free to PR to update the codes accordingly. 

The code is slightly less structured than what Andy suggested, I opted 
for Alex KISS proposal as the benchmark codes are quite simple too. 

Any proposal / update / criticism are welcome ! 
"""

### CODE REVIEW

**Comment by asmeurer** [comment]
You can actually make pull requests from other people's branches (you don't have to copy it over to your own repo first).

**Comment by aterrel** [comment]
Cool, I didn't really know how to do it, but @serge-sans-paille just committed everything to his master.

**Comment by asmeurer** [comment]
I was surprised myself when I discovered you could do it. Basically, you pull up their branch on their github page, and you can just press the pull request button as you normally would, and the pull request will be opened tracking their branch.

**Comment by serge-sans-paille** [comment]
I am closing this PR that does not stick to the (nice) way @ogrisel designed the benchmark infrastructure.

**Pull request closed without merging**
