### PR TITLE
rosen_der no longer segfaults in Parakeet

### PR DESCRIPTION
**Pull request by iskandr**
Negative indexing no longer crashes Parakeet (at least not in the obvious cases)

### CODE REVIEW

**Comment by iskandr** [comment]
@ogrisel Hey Olivier, is it possible to merge this pull request? Is there anything I should change/fix?

**Comment by serge-sans-paille** [comment]
I'll merge it once the author info are updated :-)

**Comment by ogrisel** [comment]
@serge-sans-paille the author info looks fine doesn't it?

**Comment by ogrisel** [comment]
@iskandr is there a new stable release of parakeet?

**Comment by ogrisel** [comment]
Indeed there is a new release: 0.14.2. I will merge this and rereun the benchmarks.

**Comment by serge-sans-paille** [comment]
@ogrisel yes it's fine. I thought Alex would amend its commit and missed the new one.

**Comment by ogrisel** [comment]
I pushed a new version of the bench with the new master  (the pythran errors should go away as soon as the github pages cache is invalidated).

http://numfocus.github.io/python-benchmarks/

**Comment by ogrisel** [comment]
BTW @iskandr you should add a change log to the source tree of parakeet  and include it in the long description the project to be included in the pypi page :)

**Comment by iskandr** [comment]
Ha, @ogrisel I just looked at my PyPI page. I forgot it still just says "An adorable bird that will make your children laugh and spontaneously combust". Maybe I'll add a little more detail in the next release...

Also, help me in my quest out of git ignorance-- when I update the head fork of a pull request, am I supposed to amend the last commit instead of just adding new ones?

**Comment by ogrisel** [comment]
No you do as you wish if you are the only one working on that branch. If you expect others to contribute to the same branch concurrently you should never rewrite commits (with amend or rebase).

**Pull request merged**
