### PR TITLE
Add Nathan Faggian to contributors

### PR DESCRIPTION
**Pull request by stefanv**

### CODE REVIEW

**Comment by ahmadia** [comment]
This looks good, thanks Stefan.

**Comment by aterrel** [comment]
@stefanv Thanks for noting this! We need to figure out how to add other's work with giving proper credit.  I've filed an issue on your repo that the license is unclear.  Can you please clarify?  I think it is a valuable contribution to the benchmarks.

**Comment by ogrisel** [comment]
@stefanv if you put that under MIT, then we won't have to do mixed license in here, just saying :P

**Comment by aterrel** [comment]
@ahmadia has also privately requested that we add the commit history to the files so that we can give the correct contribution via git-blame.  After the license is clarified, I will look into doing this.

**Comment by ogrisel** [comment]
Shall we merge this PR and open a new issue for the history rebasing thing?

**Comment by stefanv** [comment]
@ogrisel I just pushed a license file (MIT) to the original repository.

I think there is a small bug in the original--it does not currently converge correctly (that does not influence the benchmark).  I have someone working on it and will report back as soon as we've figured out the problem.

**Comment by ogrisel** [comment]
Thanks @stefanv, merging this PR right now.

**Pull request merged**
