### PR TITLE
Add arc_distance numpy with broadcast version and Theano version

### PR DESCRIPTION
**Pull request by nouiz**

### CODE REVIEW

**Comment by jaberg** [comment]
Looks good to me, what are the merge criteria on this project?

**Comment by jaberg** [comment]
(Should have named at least @aterrel and @ogrisel above)

**Comment by nouiz** [comment]
Where should I have named them? In github? In the author list of the file? Personally, I wouldn't butter putting author name in the file as we have the git history.

**Comment by jaberg** [comment]
Oops, I meant to ask them about merge criteria, not tell you to put their
names in the pr.

**Pull request merged**
