### PR TITLE
Addiitonnal benchmark: growcut

### PR DESCRIPTION
**Pull request by serge-sans-paille**
Numba, cython, python and pythran version are ok
parakeet version chokes on import math and continue statement

### CODE REVIEW

**Comment by ogrisel** [comment]
I fixed the pyximport for cython / numpy and merged. However I wonder if we should not disable parakeet benchmarks that do not support such python expressions. This is not a bug in parakeet but a fundamental limitation of its scope. WDYT @iskandr?

**Comment by iskandr** [comment]
Hey Olivier, 

I think having a conditional "continue" can be just replaced by wrapping the inner loop in an if-statement. I'll make a Parakeet-certified version of growcut later today.

**Comment by serge-sans-paille** [comment]
Hi Alex,
you could even automate this simple ast transformation in parakeet so 
that all tests looking like this would be valid input!
I reproduced the code in its original form for the benchmark, but I
completely agree with you that getting rid of the continue would yield a 
better looking code...

**Comment by ogrisel** [comment]
@serge-sans-paille @iskandr who wants to send a PR with the fix?

**Comment by ogrisel** [comment]
Actually, I am on it.

**Comment by ogrisel** [comment]
I fixed it (will push soon) but then:

```
 Could not run growcut_parakeet: Unsupported primitive: <built-in function sqrt>
```

**Comment by ahmadia** [comment]
@ogrisel - do you mind ensuring there is proper attribution to @stefanv and the originally hosted https://github.com/stefanv/growcut_py repository for the Python and Cython versions of the implementation?  The numba version is due to me at Continuum Analytics, and I don't know who has authored the other benchmarks.

Ideally, people are transplanting git commits from other repositories when they are easily available, but at minimum author name and email should be preserved when you guys bring these benchmarks in.

**Comment by ogrisel** [comment]
Alright.

**Comment by ogrisel** [comment]
> use numpy.sqrt instead ?

I just tried that and it fails with a an obscure error message.

**Comment by iskandr** [comment]
@ogrisel, can you use np.sqrt instead?

Also, these benchmarks are _very_ useful for finding all the things wrong
and missing in Parakeet. I picked a bad time for a major refactoring!

@serge-sans-paille https://github.com/serge-sans-paille, I've thought
about doing the control-flow to data-flow transformation for "continue" and
"break" but getting the general case right is a little tricky. The trouble
is that I put everything into SSA form directly from the Python AST so I'd
have to add some non-trivial logic there to account for control-flow
condition variables.

**Comment by ogrisel** [comment]
I just pushed a version that makes it easy to switch the implementation of sqrt (& fixed the credit).

**Comment by ogrisel** [comment]
@serge-sans-paille if I put `from math import sqrt` at the top, I get:

```
Traceback (most recent call last):
  File "run_benchmarks.py", line 77, in find_benchmarks
    module = __import__(abs_module_name, fromlist="dummy")
  File "/Users/ogrisel/code/python-benchmarks/growcut/growcut_pythran.py", line 24, in 
    '\n'.join([imports, exports, source]))
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pythran/toolchain.py", line 289, in compile_pythrancode
    module = generate_cxx(module_name, pythrancode, specs, opts)
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pythran/toolchain.py", line 149, in generate_cxx
    refine(pm, ir, optimizations)
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pythran/middlend.py", line 33, in refine
    pm.apply(ListCompToGenexp, node)
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pythran/passmanager.py", line 165, in apply
    return a.apply(node, ctx)
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pythran/passmanager.py", line 132, in apply
    return self.run(node, ctx)
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pythran/passmanager.py", line 127, in run
    n = super(Transformation, self).run(node, ctx)
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pythran/passmanager.py", line 75, in run
    self.prepare(node, ctx)
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pythran/passmanager.py", line 71, in prepare
    setattr(self, uncamel(D.__name__), d.run(rnode, ctx))
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pythran/passmanager.py", line 93, in run
    super(Analysis, self).run(node, ctx)
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pythran/passmanager.py", line 75, in run
    self.prepare(node, ctx)
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pythran/passmanager.py", line 71, in prepare
    setattr(self, uncamel(D.__name__), d.run(rnode, ctx))
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pythran/passmanager.py", line 93, in run
    super(Analysis, self).run(node, ctx)
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pythran/passmanager.py", line 76, in run
    return self.visit(node)
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pythran/passmanager.py", line 55, in visit
    return super(ContextManager, self).visit(node)
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ast.py", line 241, in visit
    return visitor(node)
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ast.py", line 249, in generic_visit
    self.visit(item)
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pythran/passmanager.py", line 55, in visit
    return super(ContextManager, self).visit(node)
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ast.py", line 241, in visit
    return visitor(node)
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pythran/analysis.py", line 545, in visit_FunctionDef
    self.generic_visit(node)
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ast.py", line 249, in generic_visit
    self.visit(item)
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pythran/passmanager.py", line 55, in visit
    return super(ContextManager, self).visit(node)
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ast.py", line 241, in visit
    return visitor(node)
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pythran/analysis.py", line 548, in visit_Assign
    value_aliases = self.visit(node.value)
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pythran/passmanager.py", line 55, in visit
    return super(ContextManager, self).visit(node)
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ast.py", line 241, in visit
    return visitor(node)
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pythran/analysis.py", line 458, in visit_Call
    self.generic_visit(node)
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ast.py", line 251, in generic_visit
    self.visit(value)
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pythran/passmanager.py", line 55, in visit
    return super(ContextManager, self).visit(node)
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ast.py", line 241, in visit
    return visitor(node)
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pythran/analysis.py", line 500, in visit_Name
    raise PythranSyntaxError(err.format(node.id), node)
PythranSyntaxError: identifier sqrt unknown, either because it is an unsupported intrinsic, the input code is faulty, or... pythran is buggy. (line 19)
```

does that mean that we need additional import declaration in the pythran wrapper, or is it a bug in pythran?

**Comment by iskandr** [comment]
Oh well, that's embarrassing. Send me the message and I'll sort this out
once Parakeet is back in one piece (hopefully later tonight).

**Comment by ogrisel** [comment]
I switched in master to use `import numpy as np` and the `np.sqrt` inline expression in the body.

Under: pythran I get:

```
Traceback (most recent call last):
  File "run_benchmarks.py", line 77, in find_benchmarks
    module = __import__(abs_module_name, fromlist="dummy")
  File "/Users/ogrisel/code/python-benchmarks/growcut/growcut_pythran.py", line 24, in 
    '\n'.join([imports, exports, source]))
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pythran/toolchain.py", line 289, in compile_pythrancode
    module = generate_cxx(module_name, pythrancode, specs, opts)
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pythran/toolchain.py", line 149, in generate_cxx
    refine(pm, ir, optimizations)
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pythran/middlend.py", line 33, in refine
    pm.apply(ListCompToGenexp, node)
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pythran/passmanager.py", line 165, in apply
    return a.apply(node, ctx)
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pythran/passmanager.py", line 132, in apply
    return self.run(node, ctx)
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pythran/passmanager.py", line 127, in run
    n = super(Transformation, self).run(node, ctx)
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pythran/passmanager.py", line 75, in run
    self.prepare(node, ctx)
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pythran/passmanager.py", line 71, in prepare
    setattr(self, uncamel(D.__name__), d.run(rnode, ctx))
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pythran/passmanager.py", line 93, in run
    super(Analysis, self).run(node, ctx)
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pythran/passmanager.py", line 75, in run
    self.prepare(node, ctx)
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pythran/passmanager.py", line 71, in prepare
    setattr(self, uncamel(D.__name__), d.run(rnode, ctx))
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pythran/passmanager.py", line 93, in run
    super(Analysis, self).run(node, ctx)
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pythran/passmanager.py", line 76, in run
    return self.visit(node)
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pythran/passmanager.py", line 55, in visit
    return super(ContextManager, self).visit(node)
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ast.py", line 241, in visit
    return visitor(node)
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ast.py", line 249, in generic_visit
    self.visit(item)
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pythran/passmanager.py", line 55, in visit
    return super(ContextManager, self).visit(node)
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ast.py", line 241, in visit
    return visitor(node)
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pythran/analysis.py", line 545, in visit_FunctionDef
    self.generic_visit(node)
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ast.py", line 249, in generic_visit
    self.visit(item)
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pythran/passmanager.py", line 55, in visit
    return super(ContextManager, self).visit(node)
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ast.py", line 241, in visit
    return visitor(node)
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pythran/analysis.py", line 548, in visit_Assign
    value_aliases = self.visit(node.value)
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pythran/passmanager.py", line 55, in visit
    return super(ContextManager, self).visit(node)
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ast.py", line 241, in visit
    return visitor(node)
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pythran/analysis.py", line 458, in visit_Call
    self.generic_visit(node)
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ast.py", line 251, in generic_visit
    self.visit(value)
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pythran/passmanager.py", line 55, in visit
    return super(ContextManager, self).visit(node)
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ast.py", line 241, in visit
    return visitor(node)
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pythran/analysis.py", line 487, in visit_Attribute
    return self.add(node, {Aliases.access_path(node)})
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pythran/analysis.py", line 393, in access_path
    return rec(modules, node)
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pythran/analysis.py", line 388, in rec
    return rec(w, n.value)[n.attr]
TypeError: string indices must be integers, not str
```

under parakeet I get:

```
Traceback (most recent call last):
  File "run_benchmarks.py", line 167, in run_benchmarks
    record = run_benchmark(name, func, args, kwargs, memory=memory)
  File "run_benchmarks.py", line 113, in run_benchmark
    first_timing = time_once()
  File "run_benchmarks.py", line 109, in time_once
    func(*args, **kwargs)
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/parakeet-0.13-py2.7.egg/parakeet/decorators.py", line 115, in __call__
    return run_function.run(self.f, *args, **kwargs)
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/parakeet-0.13-py2.7.egg/parakeet/run_function.py", line 134, in run
    untyped, _, compiled, all_args = specialize_and_compile(fn, args, kwargs)
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/parakeet-0.13-py2.7.egg/parakeet/run_function.py", line 116, in specialize_and_compile
    untyped, arg_values, arg_types = prepare_args(fn, args, kwargs)
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/parakeet-0.13-py2.7.egg/parakeet/run_function.py", line 98, in prepare_args
    untyped = ast_conversion.translate_function_value(fn)
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/parakeet-0.13-py2.7.egg/parakeet/ast_conversion.py", line 893, in translate_function_value
    filename = filename)
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/parakeet-0.13-py2.7.egg/parakeet/ast_conversion.py", line 840, in translate_function_source
    filename = filename)
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/parakeet-0.13-py2.7.egg/parakeet/ast_conversion.py", line 784, in translate_function_ast
    _, body = translator.visit_block(body)
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/parakeet-0.13-py2.7.egg/parakeet/ast_conversion.py", line 746, in visit_block
    parakeet_stmt = self.visit(stmt)
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/parakeet-0.13-py2.7.egg/parakeet/ast_conversion.py", line 487, in visit
    res = ast.NodeVisitor.visit(self, node)
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ast.py", line 241, in visit
    return visitor(node)
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/parakeet-0.13-py2.7.egg/parakeet/ast_conversion.py", line 726, in visit_For
    body, merge, _ = self.visit_loop_body(stmt.body)
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/parakeet-0.13-py2.7.egg/parakeet/ast_conversion.py", line 703, in visit_loop_body
    scope_after, body = self.visit_block(body)
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/parakeet-0.13-py2.7.egg/parakeet/ast_conversion.py", line 746, in visit_block
    parakeet_stmt = self.visit(stmt)
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/parakeet-0.13-py2.7.egg/parakeet/ast_conversion.py", line 487, in visit
    res = ast.NodeVisitor.visit(self, node)
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ast.py", line 241, in visit
    return visitor(node)
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/parakeet-0.13-py2.7.egg/parakeet/ast_conversion.py", line 726, in visit_For
    body, merge, _ = self.visit_loop_body(stmt.body)
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/parakeet-0.13-py2.7.egg/parakeet/ast_conversion.py", line 703, in visit_loop_body
    scope_after, body = self.visit_block(body)
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/parakeet-0.13-py2.7.egg/parakeet/ast_conversion.py", line 746, in visit_block
    parakeet_stmt = self.visit(stmt)
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/parakeet-0.13-py2.7.egg/parakeet/ast_conversion.py", line 487, in visit
    res = ast.NodeVisitor.visit(self, node)
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ast.py", line 241, in visit
    return visitor(node)
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/parakeet-0.13-py2.7.egg/parakeet/ast_conversion.py", line 726, in visit_For
    body, merge, _ = self.visit_loop_body(stmt.body)
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/parakeet-0.13-py2.7.egg/parakeet/ast_conversion.py", line 703, in visit_loop_body
    scope_after, body = self.visit_block(body)
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/parakeet-0.13-py2.7.egg/parakeet/ast_conversion.py", line 746, in visit_block
    parakeet_stmt = self.visit(stmt)
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/parakeet-0.13-py2.7.egg/parakeet/ast_conversion.py", line 487, in visit
    res = ast.NodeVisitor.visit(self, node)
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ast.py", line 241, in visit
    return visitor(node)
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/parakeet-0.13-py2.7.egg/parakeet/ast_conversion.py", line 726, in visit_For
    body, merge, _ = self.visit_loop_body(stmt.body)
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/parakeet-0.13-py2.7.egg/parakeet/ast_conversion.py", line 703, in visit_loop_body
    scope_after, body = self.visit_block(body)
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/parakeet-0.13-py2.7.egg/parakeet/ast_conversion.py", line 746, in visit_block
    parakeet_stmt = self.visit(stmt)
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/parakeet-0.13-py2.7.egg/parakeet/ast_conversion.py", line 487, in visit
    res = ast.NodeVisitor.visit(self, node)
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ast.py", line 241, in visit
    return visitor(node)
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/parakeet-0.13-py2.7.egg/parakeet/ast_conversion.py", line 695, in visit_If
    merge = self.create_phi_nodes(true_scope, false_scope)
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/parakeet-0.13-py2.7.egg/parakeet/ast_conversion.py", line 362, in create_phi_nodes
    right = self.lookup(name)
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/parakeet-0.13-py2.7.egg/parakeet/ast_conversion.py", line 281, in lookup
    raise NameNotFound(name)
NameNotFound: d
```

**Comment by serge-sans-paille** [comment]
It's just that you have to add the import line in the growcut_pythran.py file, where I am rebuilding the source from the original one, 

Definitively not a pythran issue, just a bad integration of pythran into the python-benchmark suite.

**Comment by iskandr** [comment]
Mine is definitely a Parakeet issue-- sqrt just isn't in the primitives map
and instead I recursively descend into numpy's python source and try to
compile it. Which, presumably, is no one's idea of desired behavior.

On Wed, Jul 10, 2013 at 1:26 PM, serge-sans-paille <notifications@github.com

**Comment by ogrisel** [comment]
Ok understood, I am fixing it.

**Comment by ogrisel** [comment]
@iskandr what about the `NameNotFound: d` exception?

**Comment by ogrisel** [comment]
Ok I fixed the `growcut_pythran` config. Now there is only the `NameNotFound: d` exception for parakeet.

**Pull request merged**
